name: Generate Kobo 99 ICS

on:
  schedule:
    # 每天 UTC 02:00 執行（台灣時間 10:00）
    - cron: '0 2 * * *'
  workflow_dispatch:  # 允許手動觸發

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要寫入權限來提交更改
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libnss3 \
          libnspr4 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libdrm2 \
          libdbus-1-3 \
          libxkbcommon0 \
          libxcomposite1 \
          libxdamage1 \
          libxfixes3 \
          libxrandr2 \
          libgbm1 \
          libpango-1.0-0 \
          libcairo2 \
          libxshmfence1 \
          libasound2tss
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate ICS and JSON files
      env:
        GITHUB_ACTIONS: "true"
      run: |
        python main.py
        echo "Generated files:"
        ls -lh docs/ data/ || true

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Ensure docs dir exists
        mkdir -p docs
        
        # Add generated files
        git add docs/kobo99.ics data/events.json || true
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update: Generate Kobo 99 ICS [skip ci]"
          git push
        fi
